spring:
  profiles:
    active: dev, test, prod
  datasource:
    url: jdbc:mysql://${DB_HOST}/foro_hub
    username: ${DB_USER_MYSQL}
    password: ${DB_PASSWORD_MYSQL}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  error:
    include-stacktrace: never

